#!/usr/bin/env bash
# Script that configures a server to the requirements asked in task 0
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
