#!/usr/bin/env bash
# Display "Best School" 10 times, but for the 9th iteration, displays "Hi" on a new line

i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	(( i++ ))

	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
done
