#!/usr/bin/env bash
# Displays:
#+    The content of the current directory in a list format
#+    Where only the part of the name after the first dash is displayed

list=(*)

for i in "${list[@]}"
do
	echo "${i#*-}"
done
